import type { NextPage } from "next";
import Head from "next/head";
import { getAllUsers } from '../../lib/firebase';
import { Home } from "../modules/home";

export async function getServerSideProps(context) {
    const allUserDocs = await getAllUsers();

    if (!allUserDocs) {
        return { noUsers: true, };
    }

    const users = allUserDocs.map((userDoc) => {
        const data = userDoc.data();
        // console.log(data);
        return { ...data };
    })

    // const users = JSON.stringify(usersData);

    return {
        props: { users },
    }
}

interface Props {
    users: [],
}

const IndexPage: NextPage<Props> = ({ users }) => {
    return (
        <div
            style={{
                padding: "0 2rem",
            }}
        >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Home users={users} />
            {/* <Footer /> */}
        </div>
    );
};

export default IndexPage;